"""Central version identifiers for reproducible artifacts."""

PROJECT_VERSION = "0.1.0"
ECONOMICS_VERSION = "economics-v1"
DGP_VERSION = "synthetic-dgp-v1"
DATASET_VERSION = "synthetic-orders-v1"
FEATURE_VERSION = "runtime-features-v1"
MODEL_VERSION = "unimplemented"
CALIBRATION_VERSION = "unimplemented"
POLICY_VERSION = "unimplemented"
CONFIG_VERSION = "scaffold-v1"
